package tests

import (
	"bytes"
	"encoding/json"
	"errors"
	"goPractice/task_manager/delivery/controllers"
	"goPractice/task_manager/domain"
	"goPractice/task_manager/mocks"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/require"
	"github.com/stretchr/testify/suite"
)

/*
here instead of creating the user usecase mock by ourselves i'm using
the mock package generated by mockery to mock the usecase layer
*/
type UserControllerSuite struct {
	suite.Suite
	httpServer *httptest.Server
	usecase    *mocks.UserUsecase
	controller *controllers.UserController
}

func (s *UserControllerSuite) SetupSuite() {

	usecase := new(mocks.UserUsecase)
	controller := controllers.NewUserController(usecase)

	router := gin.Default()
	group := router.Group("/user")
	//public
	group.POST("/register", controller.CreateUser)
	group.POST("/login", controller.UserLogin)
	//protected
	protected := group.Group("/")
	// protected.Use(infrastructure.Authorize("admin"))

	protected.GET("/", controller.GetUsers) //get all users
	protected.POST("/promote/:id", controller.PromoteUser)

	s.httpServer = httptest.NewServer(router)
	s.usecase = usecase
	s.controller = controller
}
func (s *UserControllerSuite) TearDownSuite() {
	s.httpServer.Close()
}

func (s *UserControllerSuite) TestCreateUser() {
	user := domain.User{
		Username: "testuser",
		Password: "test",
	}
	s.usecase.On("CreateUser", user).Return(user, nil)
	body, err := json.Marshal(user)
	require.NoError(s.T(), err, "Failed to marshal user")
	response, err := http.Post(s.httpServer.URL+"/user/register", "application/json", bytes.NewBuffer(body))

	require.NoError(s.T(), err, "faild to create user can't send request")
	defer response.Body.Close()

	require.Equal(s.T(), http.StatusCreated, response.StatusCode)
	s.usecase.AssertExpectations(s.T())

}
func (s *UserControllerSuite) TestGetUsers() {
	s.usecase.On("GetUsers").Return([]domain.UserOut{{Username: "user1"}, {Username: "user2"}}, nil)

	response, err := http.Get(s.httpServer.URL + "/user/")
	require.NoError(s.T(), err, "faild to make request to get users")

	defer response.Body.Close()

	require.Equal(s.T(), http.StatusOK, response.StatusCode)
	s.usecase.AssertExpectations(s.T())
}
func (s *UserControllerSuite) TestUserLogin() {
	data := domain.LoginForm{
		Username: "testuser",
		Password: "test",
	}
	s.usecase.On("Login", data).Return("token", nil)
	body, err := json.Marshal(data)
	require.NoError(s.T(), err, "Failed to marshal user")
	response, err := http.Post(s.httpServer.URL+"/user/login", "application/json", bytes.NewBuffer(body))

	require.NoError(s.T(), err, "faild to create user can't send request")
	defer response.Body.Close()

	require.Equal(s.T(), http.StatusOK, response.StatusCode)
	s.usecase.AssertExpectations(s.T())
}

// test userlogin with wrong password
func (s *UserControllerSuite) TestUserLogin_WrongPassword() {

	data := domain.LoginForm{
		Username: "testuser",
		Password: "wrongpwd",
	}
	s.usecase.On("Login", data).Return("", errors.New("wrong password"))

	body, err := json.Marshal(data)
	require.NoError(s.T(), err, "Failed to marshal user")

	response, err := http.Post(s.httpServer.URL+"/user/login", "application/json", bytes.NewBuffer(body))
	require.NoError(s.T(), err, "faild to create user can't send request")
	defer response.Body.Close()

	require.Equal(s.T(), http.StatusUnauthorized, response.StatusCode)
	s.usecase.AssertExpectations(s.T())

}

// test userlogin with wrong password
func (s *UserControllerSuite) TestUserLogin_NoFormData() {

	data := domain.LoginForm{}

	body, err := json.Marshal(data)
	require.NoError(s.T(), err, "Failed to marshal user")

	response, err := http.Post(s.httpServer.URL+"/user/login", "application/json", bytes.NewBuffer(body))
	require.NoError(s.T(), err, "faild to create user can't send request")
	defer response.Body.Close()

	require.Equal(s.T(), http.StatusBadRequest, response.StatusCode)
	s.usecase.AssertExpectations(s.T())

}
func (s *UserControllerSuite) TestPromoteUser() {
	s.usecase.On("PromoteUser", "1").Return(nil)

	response, err := http.Post(s.httpServer.URL+"/user/promote/1", "aplliction/json", nil)
	require.NoError(s.T(), err, "faild to make request to get users")

	defer response.Body.Close()

	require.Equal(s.T(), http.StatusOK, response.StatusCode)
	s.usecase.AssertExpectations(s.T())

}

func TestUserController(t *testing.T) {

	suite.Run(t, new(UserControllerSuite))

}
